name: ğŸš€ Deploy to Server (test + master)

on:
  workflow_run:
    workflows: ["ğŸ—ï¸ Build & Publish Docker"]
    types: [completed]

  push:
    branches:
      - master
      - main
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || startsWith(github.ref, 'refs/heads/feature/') }}

    steps:
      - name: ğŸš€ Deploy via SSH
        run: |
          echo "Starting deploy..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            docker pull ${{ secrets.DOCKER_USERNAME }}/pipeline-app:${{ github.run_number }} &&
            docker stop pipeline-app || true &&
            docker rm pipeline-app || true &&
            docker run -d --name pipeline-app -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/pipeline-app:${{ github.run_number }}
          "
